# Generated by Django 4.1 on 2022-12-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_services_pic_services_price2_services_price3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='pic',
        ),
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, upload_to='services/img/', verbose_name='Servicve Image'),
        ),
    ]
